"""Channel-neutral operational conversation contracts and service."""

from .adapters import NormalizedInbound, TelegramFixtureAdapter, WebFixtureAdapter
from .contracts import (
    CHANNELS,
    DELIVERY_POLICIES,
    MESSAGE_KINDS,
    AttachmentMetadata,
    ChannelBinding,
    CompressionPolicy,
    ConversationContextPolicy,
    ConversationContractError,
    ConversationCursor,
    ConversationThread,
    DeliveryReceipt,
    ExternalMessageIdentity,
    HandoffPolicy,
    MessageEnvelope,
    ParticipantIdentity,
    StateProposal,
    TranscriptExport,
    TranscriptLifecycleReceipt,
    TranscriptRetentionStatus,
    canonical_digest,
)
from .service import (
    ConversationAuthorizationError,
    ConversationConflictError,
    ConversationNotFoundError,
    ConversationService,
    IngestResult,
    default_compression_policy,
    default_context_policy,
    default_handoff_policy,
)

__all__ = [
    "CHANNELS",
    "DELIVERY_POLICIES",
    "MESSAGE_KINDS",
    "AttachmentMetadata",
    "ChannelBinding",
    "CompressionPolicy",
    "ConversationAuthorizationError",
    "ConversationConflictError",
    "ConversationContextPolicy",
    "ConversationContractError",
    "ConversationCursor",
    "ConversationNotFoundError",
    "ConversationService",
    "ConversationThread",
    "DeliveryReceipt",
    "ExternalMessageIdentity",
    "HandoffPolicy",
    "IngestResult",
    "MessageEnvelope",
    "NormalizedInbound",
    "ParticipantIdentity",
    "StateProposal",
    "TranscriptExport",
    "TranscriptLifecycleReceipt",
    "TranscriptRetentionStatus",
    "TelegramFixtureAdapter",
    "WebFixtureAdapter",
    "canonical_digest",
    "default_compression_policy",
    "default_context_policy",
    "default_handoff_policy",
]
