/**
 * Shared component surface (design.md §14). Feature agents import from here.
 */
export { BrandMark, BrandLockup } from './Brand'
export type { BrandMarkSize } from './Brand'
export { StatusBadge, StatusBadgeFrom } from './StatusBadge'
export type { StatusBadgeProps } from './StatusBadge'
export { StatusDot, StatusDotFrom } from './StatusDot'
export type { StatusDotProps } from './StatusDot'
export { OperationStateLabel } from './OperationStateLabel'
export { formatElapsed } from '@/lib/time'
export type { OperationStateLabelProps } from './OperationStateLabel'
export { CapabilityDot } from './CapabilityDot'
export type { CapabilityDotProps } from './CapabilityDot'
export { EmptyState } from './EmptyState'
export type { EmptyStateProps, EmptyStateAction } from './EmptyState'
export { ErrorState } from './ErrorState'
export type { ErrorStateProps } from './ErrorState'
export { ConfirmDialog } from './ConfirmDialog'
export type { ConfirmDialogProps } from './ConfirmDialog'
export { Drawer } from './Drawer'
export type { DrawerProps } from './Drawer'
export { Disclosure } from './Disclosure'
export type { DisclosureProps } from './Disclosure'
export { Skeleton, SkeletonRows } from './Skeleton'
export type { SkeletonProps } from './Skeleton'
export { Tooltip } from './Tooltip'
export type { TooltipProps } from './Tooltip'
export { Kbd } from './Kbd'
export { SectionHeader } from './SectionHeader'
export type { SectionHeaderProps } from './SectionHeader'
export { TimeAgo } from './TimeAgo'
export type { TimeAgoProps } from './TimeAgo'
export { CopyButton } from './CopyButton'
export { copyText } from '@/lib/clipboard'
export type { CopyButtonProps } from './CopyButton'
export { Spinner } from './Spinner'
export type { SpinnerProps } from './Spinner'
export { InlineNotice } from './InlineNotice'
export type { InlineNoticeProps } from './InlineNotice'
