"""StateBench v0 deterministic benchmark evidence primitives.

StateBench records complete configurations, paired evidence, separate
scorecards, and provenance tiers. It does not run models, load private
holdouts, or make comparative performance claims.
"""

from .aggregation import (
    PairedComparison,
    PairedComparisonAggregate,
    ResultTierEvidence,
    aggregate_paired_runs,
    classify_result_tier,
    compare_paired_runs,
)
from .models import (
    BenchmarkRunResult,
    BenchmarkSuiteManifest,
    BenchmarkTask,
    CandidateManifest,
    ConfigurationManifest,
    ResultTier,
)
from .scorecards import (
    BalancedTradeoff,
    ContextScorecard,
    CostScorecard,
    ContinuityScorecard,
    QualityScorecard,
    Scorecards,
    StateIntegrityScorecard,
    build_scorecards,
)
from .run_bundles import RunBundleIngestionError, build_execution_matrix, ingest_run_bundle
from .snapshots import (
    LOCAL_READ_ONLY_PROVENANCE,
    SNAPSHOT_CONFIGURATION_FORMAT,
    CompatibilityMode,
    LocalReadOnlySnapshotResolver,
    SnapshotConfiguration,
    SnapshotResolutionError,
)
from .git_fixtures import (
    FixtureMaterialization,
    GitBundleFixtureMaterializer,
    GitFixtureError,
    RemoteEqualityFacts,
    TemporaryBareRemote,
)
from .interruption import (
    INTERRUPTION_POLICY_FORMAT,
    INTERRUPTION_RECORD_FORMAT,
    AttemptIdentity,
    ContinuationAttempt,
    ContinuationProtocolError,
    EvidenceReference,
    ForcedInterruptionHarness,
    InterruptionController,
    InterruptionFact,
    InterruptionPolicy,
    InterruptionSignal,
    LauncherStageResult,
    RepositorySnapshot,
    StageAInput,
    StageALauncher,
    StageBInput,
    StageBLauncher,
)
from .evaluator import (
    ALPHA_SUITE_FORMAT,
    EVALUATOR_FORMAT,
    REPORT_BANNER,
    AlphaCaseGenerator,
    BenchmarkCase,
    BenchmarkComparison,
    BenchmarkReport,
    BenchmarkRunSpec,
    BenchmarkSuite,
    CalibrationConfiguration,
    CommandOutcome,
    CriticalViolation,
    CriticalViolationCode,
    EvaluatorAuthority,
    ExternalEvaluator,
    EvidenceReference as EvaluatorEvidenceReference,
    EvaluatorResult,
    EvaluationObservation,
    HELD_CONSTANT_CONFIGURATION,
    HeldConstantConfiguration,
    MetricObservation,
    ObservationQuality,
    RuntimeBudgets,
    RuntimeComponent,
    alpha_configurations,
    generate_alpha_calibration,
    run_evaluator_command,
)
from .real_project_models import (
    REAL_PROJECT_BANNER,
    REAL_PROJECT_HANDOFF_FORMAT,
    REAL_PROJECT_METRICS_FORMAT,
    REAL_PROJECT_REPORT_FORMAT,
    REAL_PROJECT_RUN_FORMAT,
    REAL_PROJECT_SCENARIO_FORMAT,
    REAL_PROJECT_TRACE_FORMAT,
    AttemptAccounting as RealProjectAttemptAccounting,
    AttemptTrace as RealProjectAttemptTrace,
    BacklogDecisionTrace as RealProjectBacklogDecisionTrace,
    ClosureTrace as RealProjectClosureTrace,
    ContextMetrics as RealProjectContextMetrics,
    DelegationTrace as RealProjectDelegationTrace,
    EfficiencyMetrics as RealProjectEfficiencyMetrics,
    HandoffArtifact as RealProjectHandoffArtifact,
    HardOutcomes as RealProjectHardOutcomes,
    HumanIntervention as RealProjectHumanIntervention,
    OrchestrationMetrics as RealProjectOrchestrationMetrics,
    ParentJobAccounting,
    ProjectBootstrapTrace,
    ProjectMilestone,
    RealProjectCalibrationReport,
    RealProjectContractError,
    RealProjectMetrics,
    RealProjectRunResult,
    RealProjectScenario,
    RealProjectTrace,
    RealProjectWorkflowConfiguration,
    RepairTrace as RealProjectRepairTrace,
    ReviewTrace as RealProjectReviewTrace,
    SliceSelectionTrace as RealProjectSliceSelectionTrace,
)
from .real_project_harness import (
    REAL_PROJECT_FIXTURE_FORMAT,
    PreparedRealProjectFixture,
    RealProjectFixtureBuilder,
    SyntheticRealProjectHarness,
    generate_real_project_calibration,
)
from .devloop import (
    DEVLOOP_COLLECTOR_VERSION,
    DEVLOOP_EVALUATION_FORMAT,
    DEVLOOP_EVALUATOR_VERSION,
    DEVLOOP_METRIC_UNITS,
    DEVLOOP_TRACE_FORMAT,
    DevLoopCollectionError,
    DevLoopCollectionFailure,
    DevLoopCollectionSpec,
    DevLoopCollector,
    DevLoopCommitFact,
    DevLoopEvaluationReport,
    DevLoopEvaluator,
    DevLoopMetricEvidence,
    DevLoopStructuralTrace,
    PathClassification,
    classify_path,
    structural_trace_from_dict,
)

__all__ = [
    "BalancedTradeoff",
    "BenchmarkRunResult",
    "BenchmarkSuiteManifest",
    "AttemptIdentity",
    "BenchmarkTask",
    "CandidateManifest",
    "CompatibilityMode",
    "ConfigurationManifest",
    "ContextScorecard",
    "CostScorecard",
    "ContinuityScorecard",
    "ContinuationAttempt",
    "ContinuationProtocolError",
    "EvidenceReference",
    "FixtureMaterialization",
    "GitBundleFixtureMaterializer",
    "GitFixtureError",
    "ForcedInterruptionHarness",
    "INTERRUPTION_POLICY_FORMAT",
    "INTERRUPTION_RECORD_FORMAT",
    "InterruptionController",
    "InterruptionFact",
    "InterruptionPolicy",
    "InterruptionSignal",
    "LauncherStageResult",
    "LOCAL_READ_ONLY_PROVENANCE",
    "LocalReadOnlySnapshotResolver",
    "RunBundleIngestionError",
    "PairedComparison",
    "PairedComparisonAggregate",
    "QualityScorecard",
    "ResultTier",
    "ResultTierEvidence",
    "RepositorySnapshot",
    "RemoteEqualityFacts",
    "SNAPSHOT_CONFIGURATION_FORMAT",
    "Scorecards",
    "StateIntegrityScorecard",
    "StageAInput",
    "StageALauncher",
    "StageBInput",
    "StageBLauncher",
    "SnapshotConfiguration",
    "SnapshotResolutionError",
    "TemporaryBareRemote",
    "aggregate_paired_runs",
    "build_scorecards",
    "build_execution_matrix",
    "classify_result_tier",
    "compare_paired_runs",
    "ingest_run_bundle",
    "ALPHA_SUITE_FORMAT",
    "EVALUATOR_FORMAT",
    "REPORT_BANNER",
    "AlphaCaseGenerator",
    "BenchmarkCase",
    "BenchmarkComparison",
    "BenchmarkReport",
    "BenchmarkRunSpec",
    "BenchmarkSuite",
    "CalibrationConfiguration",
    "CommandOutcome",
    "CriticalViolation",
    "CriticalViolationCode",
    "EvaluatorAuthority",
    "ExternalEvaluator",
    "EvaluatorEvidenceReference",
    "EvaluatorResult",
    "EvaluationObservation",
    "HELD_CONSTANT_CONFIGURATION",
    "HeldConstantConfiguration",
    "MetricObservation",
    "ObservationQuality",
    "RuntimeBudgets",
    "RuntimeComponent",
    "alpha_configurations",
    "generate_alpha_calibration",
    "run_evaluator_command",
    "REAL_PROJECT_BANNER",
    "REAL_PROJECT_FIXTURE_FORMAT",
    "REAL_PROJECT_HANDOFF_FORMAT",
    "REAL_PROJECT_METRICS_FORMAT",
    "REAL_PROJECT_REPORT_FORMAT",
    "REAL_PROJECT_RUN_FORMAT",
    "REAL_PROJECT_SCENARIO_FORMAT",
    "REAL_PROJECT_TRACE_FORMAT",
    "ParentJobAccounting",
    "PreparedRealProjectFixture",
    "ProjectBootstrapTrace",
    "ProjectMilestone",
    "RealProjectAttemptAccounting",
    "RealProjectAttemptTrace",
    "RealProjectBacklogDecisionTrace",
    "RealProjectCalibrationReport",
    "RealProjectClosureTrace",
    "RealProjectContextMetrics",
    "RealProjectContractError",
    "RealProjectDelegationTrace",
    "RealProjectEfficiencyMetrics",
    "RealProjectFixtureBuilder",
    "RealProjectHandoffArtifact",
    "RealProjectHardOutcomes",
    "RealProjectHumanIntervention",
    "RealProjectMetrics",
    "RealProjectOrchestrationMetrics",
    "RealProjectRepairTrace",
    "RealProjectReviewTrace",
    "RealProjectRunResult",
    "RealProjectScenario",
    "RealProjectSliceSelectionTrace",
    "RealProjectTrace",
    "RealProjectWorkflowConfiguration",
    "SyntheticRealProjectHarness",
    "generate_real_project_calibration",
    "DEVLOOP_COLLECTOR_VERSION",
    "DEVLOOP_EVALUATION_FORMAT",
    "DEVLOOP_EVALUATOR_VERSION",
    "DEVLOOP_METRIC_UNITS",
    "DEVLOOP_TRACE_FORMAT",
    "DevLoopCollectionError",
    "DevLoopCollectionFailure",
    "DevLoopCollectionSpec",
    "DevLoopCollector",
    "DevLoopCommitFact",
    "DevLoopEvaluationReport",
    "DevLoopEvaluator",
    "DevLoopMetricEvidence",
    "DevLoopStructuralTrace",
    "PathClassification",
    "classify_path",
    "structural_trace_from_dict",
]
