#!/usr/bin/env python3
"""Extend, never replace, the manifest behind the immutable-release-bytes gate.

WHY THIS EXISTS. The campaign cites `sha256sum -c` exiting 0 against
``~/.local/state/stateport/immutable-set.sha256`` as proof that "Signed Alpha.15/16/17/18 and every
earlier published byte" are untouched. That exit code is real and the 167 entries it covers do verify,
but the manifest was hand-authored, is untracked, has not been extended since 2026-09-12, and is
written by no script: it names 167 files of a 247,972-file release tree, overlaps the immutable
artifact classes in only 11 places, and covers ZERO signed release-index payloads. A gate that
verifies 0.07% of the tree and calls the result "every earlier published byte" is a false negative
generator, not an immutability check. See
``evidence/one-line-release-001/constraint-audit-20260926.md``.

THE DECLARED SCOPE. This module pins exactly the three artifact classes the project contract calls
immutable, and nothing else:

  1. ``release-index.signed-payload.json``  -- the signed release-index payload. This is the byte
     that is actually signed and published; a change here is a change to a released claim.
  2. ``release-index.json``                 -- the release index itself.
  3. ``*.sigstore.json``                    -- sigstore signature bundles for those payloads.

THE SCOPE DELIBERATELY EXCLUDES build intermediates, receipts and evidence JSON. Those are
regenerated by design: a receipt, a guard result, a candidate-input manifest and an evidence
document are records OF a run, not published bytes, and a new alpha legitimately produces new ones.
Pinning 247,972 digests over them would be noise, not assurance -- a manifest that changes on every
build trains its readers to re-baseline it, which is exactly how an immutability check dies. The
excluded classes are still covered here in the narrower sense that matters: every one of them that is
ALREADY in the manifest stays pinned, forever, because the output is a union.

THE RULE THAT SHAPES THE CODE. A manifest regenerated in order to make a gate pass is not a check.
So this generator is EXTEND-ONLY and FAIL-CLOSED:

  * the output is the UNION of the existing manifest and the declared scope. An existing entry is
    dropped only if the file it names is GONE from disk, and that case is a refusal, not a drop;
  * every existing entry is re-verified BEFORE anything is computed. If a single one is gone or
    mismatched, the build raises and no output is produced. The refusal is unconditional: there is no
    flag, no force, no ``--replace`` that bypasses it, because the one thing this module must never
    do is re-baseline a changed byte and call the result clean;
  * a scoped file that cannot be read, or that is not a regular non-symlink file, is likewise a
    refusal, so a symlink cannot launder an out-of-tree target into a pinned digest;
  * writing requires an explicit ``--replace``, and only ever happens after the interlock passes.

``--check`` is the mode a CI job or pre-commit hook wants: it verifies an existing manifest against
the tree and exits non-zero on any gone-or-mismatched entry, writing nothing at all.

DETERMINISM. Output is sorted by relative path in Python code-point order (byte order for the ASCII
paths in play), not by the ambient locale, so the same tree yields byte-identical output on any
host. The live manifest was locale-sorted; that is a cosmetic difference and this module does not
re-sort history, it adds to it.
"""
from __future__ import annotations

import argparse
from dataclasses import dataclass
import fnmatch
import hashlib
import os
from pathlib import Path
import stat
import sys
from typing import Mapping, Sequence

#: Declared scope, as (kind, pattern) pairs. ``fnmatch`` is applied to the BASENAME only, so a
#: pattern can never reach across a directory boundary. These three classes are the whole scope;
#: adding a fourth is a contract change, not a convenience.
SCOPE: tuple[tuple[str, str], ...] = (
    ("signed_payload", "release-index.signed-payload.json"),
    ("release_index", "release-index.json"),
    ("sigstore_bundle", "*.sigstore.json"),
)

_READ_CHUNK = 1 << 20


class ImmutableSetError(RuntimeError):
    """Raised when the generator must refuse: the interlock fired, or the scope is unreadable."""


@dataclass(frozen=True)
class Plan:
    """The proposed manifest and the arithmetic behind it.

    There is deliberately no ``dropped`` field: a plan cannot exist in which an existing entry went
    missing, because ``plan`` is only ever reached after the interlock has verified every one of
    them. A dropped entry is a refusal that stops the run, not a line that quietly disappears.
    """

    text: str
    entries: dict[str, str]
    scoped: tuple[str, ...]
    added: tuple[str, ...] = ()
    kept: tuple[str, ...] = ()


def _is_scoped(basename: str) -> bool:
    for _kind, pattern in SCOPE:
        if fnmatch.fnmatchcase(basename, pattern):
            return True
    return False


def scoped_paths(root: str | os.PathLike[str]) -> list[str]:
    """Return the sorted relative POSIX paths under ``root`` that fall in the declared scope.

    Symlinked directories are not followed, so a link cannot pull an out-of-tree tree into the
    scope. Entries that match the scope by NAME are returned whatever their type; deciding whether a
    symlink or a device may be pinned is ``digest_file``'s job, and it refuses.
    """
    base = Path(root)
    if not base.is_dir():
        raise ImmutableSetError(f"release root is not a directory: {base}")
    found: list[str] = []
    for dirpath, dirnames, filenames in os.walk(base, followlinks=False):
        dirnames[:] = sorted(d for d in dirnames if not os.path.islink(os.path.join(dirpath, d)))
        for name in sorted(filenames):
            if _is_scoped(name):
                full = os.path.join(dirpath, name)
                found.append(os.path.relpath(full, base).replace(os.sep, "/"))
    found.sort()
    return found


def digest_file(path: str | os.PathLike[str]) -> str:
    """Return the sha256 of a regular file, refusing anything that is not one.

    A symlink is refused rather than followed: hashing its target would pin a byte that lives
    outside the release tree, and the next verification would depend on a file the manifest never
    named.
    """
    full = Path(path)
    try:
        info = os.lstat(full)
    except OSError as exc:
        raise ImmutableSetError(f"cannot stat {full}: {exc}") from exc
    if stat.S_ISLNK(info.st_mode):
        raise ImmutableSetError(f"refusing to pin a symlink: {full}")
    if not stat.S_ISREG(info.st_mode):
        raise ImmutableSetError(f"refusing to pin a non-regular file: {full}")
    digest = hashlib.sha256()
    try:
        with open(full, "rb") as handle:
            while chunk := handle.read(_READ_CHUNK):
                digest.update(chunk)
    except OSError as exc:
        raise ImmutableSetError(f"cannot read {full}: {exc}") from exc
    return digest.hexdigest()


def _unescape(name: str) -> str:
    """Undo GNU coreutils' sha256sum escaping of backslash and newline in file names."""
    if not name.startswith("\\"):
        return name
    body = name[1:]
    out: list[str] = []
    index = 0
    while index < len(body):
        char = body[index]
        if char == "\\" and index + 1 < len(body) and body[index + 1] in ("\\", "n"):
            out.append("\\" if body[index + 1] == "\\" else "\n")
            index += 2
            continue
        out.append(char)
        index += 1
    return "".join(out)


def read_manifest(path: str | os.PathLike[str]) -> dict[str, str]:
    """Parse a ``sha256sum`` manifest into ``{relative_path: digest}``.

    Tolerates the two-space text format and the ``*`` binary-mode marker. A duplicate path carrying
    two different digests is a contradiction, not a last-writer-wins, and raises.
    """
    text = Path(path).read_text(encoding="utf-8")
    entries: dict[str, str] = {}
    for number, raw in enumerate(text.splitlines(), start=1):
        if not raw.strip():
            continue
        digest, separator, name = raw.partition("  ")
        if not separator or len(digest) != 64:
            # A single-space manifest is a different format; guessing at it is how a manifest
            # silently loses half its entries.
            raise ImmutableSetError(f"{path}:{number}: not a sha256sum manifest line: {raw!r}")
        if any(character not in "0123456789abcdef" for character in digest):
            raise ImmutableSetError(f"{path}:{number}: not a hex sha256: {digest!r}")
        relative = _unescape(name.lstrip("*") if name.startswith("*") else name)
        previous = entries.get(relative)
        if previous is not None and previous != digest:
            raise ImmutableSetError(
                f"{path}:{number}: {relative} is listed twice with different digests"
            )
        entries[relative] = digest
    return entries


def _safe_join(root: Path, relative: str) -> Path:
    if os.path.isabs(relative):
        raise ImmutableSetError(f"manifest entry is an absolute path and cannot be verified: {relative}")
    candidate = (root / relative).resolve()
    root_resolved = root.resolve()
    if candidate != root_resolved and root_resolved not in candidate.parents:
        raise ImmutableSetError(f"manifest entry escapes the release root and cannot be verified: {relative}")
    return root / relative


def verify_existing(
    root: str | os.PathLike[str], manifest: Mapping[str, str]
) -> tuple[list[str], list[str]]:
    """Return ``(gone, mismatched)``: the entries that fail, in sorted order.

    This is the safety interlock, and the whole reason the module exists. ``mismatched`` means the
    byte behind a pinned path changed; ``gone`` means the path no longer exists. Neither is
    something a generator may resolve on its own, because the only way to make either one disappear
    is to stop looking.
    """
    base = Path(root)
    gone: list[str] = []
    mismatched: list[str] = []
    for relative in sorted(manifest):
        expected = manifest[relative]
        full = _safe_join(base, relative)
        if not os.path.lexists(full):
            gone.append(relative)
            continue
        try:
            actual = digest_file(full)
        except ImmutableSetError:
            # Unreadable, or a symlink where a pinned regular file used to be: not a pass. It is
            # reported as a mismatch so the caller refuses to regenerate.
            mismatched.append(relative)
            continue
        if actual != expected:
            mismatched.append(relative)
    return gone, mismatched


def interlock(root: str | os.PathLike[str], manifest: Mapping[str, str]) -> None:
    """Raise unless every existing entry still verifies byte-for-byte."""
    gone, mismatched = verify_existing(root, manifest)
    if gone or mismatched:
        lines = [f"immutable-set interlock: refusing to regenerate ({len(gone)} gone, {len(mismatched)} mismatched)"]
        lines += [f"  gone:       {path}" for path in gone]
        lines += [f"  mismatched: {path}" for path in mismatched]
        lines.append(
            "A changed published byte is evidence, not a formatting problem. Resolve it in the "
            "record; do not re-baseline the manifest to make this message go away."
        )
        raise ImmutableSetError("\n".join(lines))


def plan(root: str | os.PathLike[str], existing: Mapping[str, str] | None = None) -> Plan:
    """Compute the proposed UNION manifest, or raise. Never writes anything.

    Raises ``ImmutableSetError`` if any existing entry is gone or mismatched, or if any scoped file
    cannot be hashed.
    """
    base = Path(root)
    entries: dict[str, str] = {}
    if existing:
        interlock(base, existing)
        entries.update(existing)
    scoped = scoped_paths(base)
    added: list[str] = []
    for relative in scoped:
        digest = digest_file(base / relative)
        if relative not in entries:
            added.append(relative)
        entries[relative] = digest
    kept = tuple(sorted(existing)) if existing else ()
    return Plan(
        text=render_manifest(entries),
        entries=entries,
        scoped=tuple(scoped),
        added=tuple(added),
        kept=kept,
    )


def build_manifest(
    root: str | os.PathLike[str], existing: Mapping[str, str] | None = None
) -> str:
    """Return the union of ``existing`` and the declared scope as ``sha256sum`` text.

    Refuses, rather than returning a partial or a re-baselined manifest, when an existing entry is
    gone or mismatched. Writing is the caller's business and only happens after this returns.
    """
    return plan(root, existing).text


def render_manifest(entries: Mapping[str, str]) -> str:
    """Render ``{path: digest}`` as ``sha256sum`` text, sorted by path in code-point order."""
    return "".join(f"{entries[path]}  {path}\n" for path in sorted(entries))


def _write_atomically(path: Path, text: str) -> None:
    temporary = path.with_name(path.name + ".tmp-immutable-set")
    with open(temporary, "w", encoding="utf-8") as handle:
        handle.write(text)
        handle.flush()
        os.fsync(handle.fileno())
    os.replace(temporary, path)


def main(argv: Sequence[str] | None = None) -> int:
    """Verify and, when asked and safe, extend the manifest. Returns a process exit code."""
    parser = argparse.ArgumentParser(
        description="Extend the immutable-release-bytes manifest; never re-baseline it."
    )
    parser.add_argument("root", help="release tree root, e.g. ~/.local/state/stateport/release")
    parser.add_argument(
        "-o",
        "--output",
        required=True,
        help="path of the manifest to verify, and (with --replace) to extend",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify only: report the scope and the proposed union, write nothing, exit non-zero "
        "if any pinned entry is gone or mismatched",
    )
    parser.add_argument(
        "--replace",
        action="store_true",
        help="permit overwriting an existing output file; still refused if the interlock fires",
    )
    arguments = parser.parse_args(argv)

    root = Path(arguments.root)
    output = Path(arguments.output)
    if not output.exists():
        if arguments.check:
            print(f"manifest not found: {output}", file=sys.stderr)
            return 2
        existing: Mapping[str, str] = {}
    else:
        try:
            existing = read_manifest(output)
        except (ImmutableSetError, OSError) as exc:
            print(f"refusing: {exc}", file=sys.stderr)
            return 2

    try:
        proposed = plan(root, existing)
    except ImmutableSetError as exc:
        print(str(exc), file=sys.stderr)
        return 1

    kept = len(proposed.kept)
    print(f"release root:      {root}")
    print(f"manifest:          {output}")
    print(f"existing entries:  {kept}")
    print(f"  verified:        {kept}   (0 gone, 0 mismatched)")
    print(f"scoped entries:    {len(proposed.scoped)}  (declared scope: {len(SCOPE)} classes)")
    for kind, pattern in SCOPE:
        print(f"    {kind}: {pattern}")
    print(f"union entries:     {len(proposed.entries)}")
    print(f"  added:           {len(proposed.added)}")
    print(f"  dropped:         0   (extend-only; a vanished entry is a refusal, never a drop)")

    if arguments.check:
        print("check mode: nothing written.")
        return 0

    if output.exists() and not arguments.replace:
        print(
            f"refusing to overwrite {output} without --replace. "
            "The coordinator applies the extended manifest; this tool does not bless bytes silently.",
            file=sys.stderr,
        )
        return 2
    if output.exists() and proposed.text == output.read_text(encoding="utf-8"):
        print("manifest already current; nothing written.")
        return 0
    try:
        _write_atomically(output, proposed.text)
    except OSError as exc:
        print(f"refusing to write {output}: {exc}", file=sys.stderr)
        return 2
    print(f"wrote {len(proposed.entries)} entries to {output}")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
